<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<!-- 
  //***		Author:      John Booz
  //***		Date:        05/25/2015
  //***		Filename:    register.php
  //***		Description: PHP file to display form to register user  
-->
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>theCollegeRoar - Terms of Use</title>
  <?php include 'loadLinks.php'; ?>
</head>

<body>
  <?php include 'header.php'; ?>
  <div id="main">
		<div id="links">
			<a href="https://www.google.com">Google</a>
			<a href="https://www.ESPN.com">ESPN</a>
			<a href="https://www.yahoo.com">Yahoo!</a>
			<a href="https://www.wired.com">Wired</a>
		</div>

		<div id="article">
			<div id="termsuse">
    	  		  <p>These Terms of Use apply to the The College Roar website at www.thecollegeroar.com and all associated sites linked to www.thecollegeroar.com by The College Roar, and its subsidiaries and affiliates.  The College Roar website and affiliated sites are referred to collectively as the &quotSite.&quot Your access to the Site and use of the services and tools provided on the Site is governed by the following Terms of Service Agreement (the &quotAgreement&quot), which may be amended by The College Roar from time to time at its sole and absolute discretion.</P>
            	  <p>In addition to the Services we provide directly to You, we may also serve as a service provider for a variety of educational institutions (&quotInstitutions&quot).  These Institutions have entered into separate written agreements with The College Roar governing those services provided by The College Roar. This Agreement does not apply to those services provided to the Institution but do not apply to your access to or use of the Site or Services that is not on behalf of the Institution. This Agreement does not alter in any way the terms and conditions of any other agreement your Institution may have with The College Roar.   If there is a conflict between this Agreement and any other agreement your Institution may have with The College Roar, the terms of the other agreement shall control for that conflict.  The current version of this Agreement is always available at www.thecollegeroar.com</P>
            	  <p>Please read the following terms and conditions carefully. By accessing the Site or using any of the products and services provided on, or made available via, the Site (individually and collectively, the &quotServices&quot), you agree to be bound by the then current terms and conditions of this Agreement (except as otherwise agreed to in writing with Parchment), and your continued access to the Site and/or use of such Services constitute your acceptance of any additional or different terms and conditions added to this Agreement in the future. If you are under the age of 18 or the age of majority in your jurisdiction, your parent or legal guardian must agree to the terms of this user agreement before you may use the website.  If you do not accept all of the terms and conditions of this Agreement, do not register on the Site, purchase the Services offered on the Site or access any portion of the Site which may be password-restricted., YOUR ACCESS TO THE SITE OR USE OF ANY SERVICES ON THE SITE CONSTITUTES YOUR AND, WHERE APPROPRIATE, YOUR PARENT&rsquo;S ACCEPTANCE OF THESE TERMS AND CONDITIONS.</P>
            	  <p>Your use of, and participation in, certain Services may be subject to additional terms (&quotSupplemental Terms&quot) and such Supplemental Terms will either be listed in this Agreement or will be presented to you for your acceptance when you sign up to use the supplemental Service.  If this Agreement is inconsistent with such Supplemental Terms, the Supplemental Terms shall control with respect to such Service.</P>
            	  <p>1. DESCRIPTION OF SERVICES</p>
            	  <p>The College Roar makes available statistics and data for colleges and universities on acceptance rates, financial aid and graduations rates. Access to information is password restricted to persons who: (i) are at least 13 years old (and, where applicable, have the required parental consent), (ii) register with The College Roar, and (iii) accept and abide by all of the terms and conditions of this Agreement (&quotRegistered Users&quot). Unless explicitly stated otherwise, any new features that augment or enhance the current Services, including the release of new The College Roar products, services, tools or properties directed at Registered Users or visitors of the Site, shall be subject to this Agreement. The College Roar is under no obligation to update the Site, the Services or any information or data contained on the Site or used in connection with the Services. The College Roar reserves the right at any time and from time to time to modify, discontinue or suspend, temporarily or permanently, its offering of the Services (or any part thereof) without notice or liability to you or any third party.</p>
            	  <p>2. YOUR REGISTRATION OBLIGATIONS</p>
            	  <p>By completing the registration process for the use of any Services where access to educational records will be necessary, you represent that you are eligible to do so under the Family Education Rights and Privacy Act (&quotFERPA&quot). You also agree to provide true, accurate, current and complete information about yourself as prompted by the applicable registration form and maintain and promptly update such information to keep it true, accurate, current and complete. If you provide any information that is untrue, inaccurate, not current or incomplete, or if The College Roar has reasonable grounds to suspect that such information is untrue, inaccurate, not current or incomplete, The College Roar has the right to suspend or terminate your account and refuse any and all current or future use of all or any of the Services.
            	  <p>3. THE COLLEGE ROAR PRIVACY POLICY</P>
            	  <p>All information about you including your registration information and any information stored or transmitted in any way on the Site is subject to our Privacy Policy, located at www.thecollegeroar.com.
            	  <p>4. REGISTERED USER ACCOUNT, PASSWORD AND SECURITY</p>
            	  <p>You will receive a password protected Registered User account and a user ID upon completing the registration process. You agree to: (i) maintain the confidentiality of your password, (ii) take full responsibility for all activities by users accessing the Site or the Services through your account(s) (including, without limitation your Registered User account, if applicable), (iii) immediately notify The College Roar of any unauthorized use of your account or any other breach of security that you become aware of, and (iv) ensure that you exit from your account at the end of each session. Failure to exit your account can enable the next user of the computer to access and modify information in your account. The College Roar is not responsible for any loss or damage arising from your failure to comply with these requirements. You are responsible for all activities that occur under your account. You may not share your account or password with anyone, and you agree to (1) notify The College Roar immediately of any unauthorized use of your password or any other breach of security; and (2) exit from your account at the end of each session.</p>
            	  <p>Notwithstanding anything to the contrary herein, you acknowledge and agree that you shall have no ownership or other property interest in your Account, and you further acknowledge and agree that all rights in and to your Account are and shall forever be owned by and inure to the benefit of The College Roar.</p>
            	  <p>5. CONTENT, USE OF SITE</p>
            	  <p>You, and not The College Roar, are solely responsible for all the information, data, text, messages, emails or other communications or materials (&quotContent&quot) that you create, link to, transmit or make available by any method on or through the Site (&quotYour Content&quot) and other users of the Site, and not The College Roar, are similarly responsible for all Content they make available through the Site (&quotUser Content&quot). You acknowledge that except as may be set forth in a separate written agreement between The College Roar and you, The College Roar may, but is not required to, pre-screen Content posted on the Site or transmitted through the Services and is not obligated or responsible to verify the accuracy, reliability, timeliness or appropriateness of such Content. Without limiting the foregoing, you also agree that The College Roar may in its sole discretion refuse to post, store or transmit any Content submitted by you, or move, remove, edit or modify any Content on the Site as The College Roar deems appropriate.
            	  <p>The College Roar does not claim ownership of Your Content. However, when you post or publish Your Content on or in the Site or Services, you represent that you have a royalty-free, perpetual, irrevocable, worldwide, non-exclusive right (including any moral rights) and license to use, license, reproduce, modify, adapt, publish, translate, create derivative works from, distribute, derive revenue or other remuneration from, and communicate to the public, perform and display Your Content (in whole or in part) worldwide and/or to incorporate it in other works in any form, media or technology now known or later developed, for the full term of any worldwide intellectual property right that may exist in Your Content. You agree that you, not The College Roar, are responsible for all of Your Content that you make available on or in the Site or Services, whether publicly posted or privately transmitted.
            	  <p>You will not use the Site and/or the Services to:</br>
            	  (a)  access, store or transmit any Content that is unlawful, harmful, threatening, abusive, harassing, tortious, defamatory, vulgar, obscene, libelous, invasive of another&rsquo;s privacy, hateful, or racially, ethnically or otherwise objectionable;</br>
            	  (b)  impersonate any person or entity including, without limitation, any The College Roar employee, agent, or affiliate, or falsely state or otherwise misrepresent your affiliation with a person or entity;</br>
            	  (c)  access, store or transmit any Content that you do not have a right to collect, use, store or transmit under any law or under any contractual or fiduciary relationships (including, without limitation, academic and transcript information and data and other confidential information);</br>
            	  (d)  access, store or transmit any Content that infringes any intellectual and/or industrial property rights of any kind anywhere in the world of any third party;</br>
            	  (e)  store or transmit any unsolicited or unauthorized advertising, promotional materials, &quotjunk mail,&quot &quotspam,&quot &quotchain letters,&quot &quotpyramid schemes,&quot or any other form of solicitation;</br>
            	  (f)  access, store or transmit any Content that contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer software or hardware or telecommunications equipment;</br>
            	  (g)  interfere with or disrupt the Site, the Services or any servers or networks connected to the Site or used with the Services, or disobey any requirements, procedures, policies or regulations of any networks connected to the Site or used with the Services; or</br>
            	  (h)  violate any applicable local, state, national or international law including, without limitation, regulations promulgated by the U.S. Securities and Exchange Commission, any rules of any national or other securities exchange, and any other regulations having the force of law.</p>
            	  <p>6. NOTICE</p>
            	  <p>If The College Roar receives notice that Content is not in keeping with the Terms of Use or the intended use of the Discussion section where it is posted, we reserve the right to remove the Content.  If you think we have published Content that infringes your copyright, we will address your concerns; however, if we believe that our use is legitimate, we will not remove it from the Site.</p>
            	  <p>Please note that we will respond only to notices of alleged infringement that comply with the Digital Millenium Copyright Act (go to www.copyright.gov for the complete text of the Act).</p>
            	  <p>To file a notice of infringement with us, you must provide a written communication (via fax or email with a signed PDF) to our designated copyright agent that sets forth the following:</br>
            	  (1)    A detailed description of the copyrighted work that is allegedly infringed upon;</br>
            	  (2)    A description of the location of the allegedly infringing material on the Site;</br>
            	  (3)    Your contact information, including your address, telephone number, and, if available, email address (Note that this contact information is for suspected copyright infringement only. Contact information for other matters is provided elsewhere in these Terms of Use or on the Site);</br>
            	  (4)    A statement by you indicating that you have a good-faith belief that the allegedly infringing use is not authorized by the copyright owner, its agent, or the law;</br>
            	  (5)    A statement by you, made under the penalty of perjury, affirming that the information in your notice is accurate and that you are authorized to act on the copyright owner&rsquo;s behalf; and</br>
            	  (6)    An electronic or physical signature of the copyright owner or someone authorized on the owner&rsquo;s behalf to assert infringement of copyright and to submit the statement.</P>
            	  <p>For copyright inquiries under the Digital Millenium Copyright Act contact:</p>
            	  <p>Copyright Agent</br>
            	  The College Roar</br>
            	  2518 Crafton Drive</br>
            	  Bensalem, PA 19020</p>
            	  <p>Please note that you will be liable for damages (including costs and attorneys&rsquo; fees) if you materially misrepresent that any material on our site is infringing on your copyrights.</p>
            	  <p>We also reserve the right to publish your letter on the Site.</p>
        	
	<p>7. REGISTERED USER CONDUCT AND USE OF THE SITE</p>
	
	<p>The College Roar takes the safety and security of its Registered Users and online visitors very seriously. If The College Roar believes that a Registered User of any account or visitor to the Site is harassing, deceiving, harming or otherwise endangering the physical or emotional well-being of any other person directly or indirectly through the Site or the Services, The College Roar (in its sole discretion) may notify the appropriate law enforcement authorities and cooperate to the full extent requested by such authorities in their investigation of such allegations and in any resulting criminal actions, or at The College Roar&rsquo;s sole discretion, at the request of third parties in any resulting civil action. Such cooperation may include, without limitation, the disclosure of personally identifying information and/or private communications transmitted through the Site.</p>
	<p>8. INDEMNITY</p>
	<p>You agree to indemnify, defend and hold The College Roar (and its parents, subsidiaries, affiliates, officers, directors, shareholders, agents, partners, customers and employees) harmless from any claim, demand, suit, damages, losses and costs (including reasonable attorneys&rsquo; fees) made by any third party due to or arising out of (i) your violation of this Agreement or Your Content or (ii) your violation of any law or the rights of any person or entity arising out of or related to the use of the Site or Services. The College Roar reserves the right to assume the exclusive defense and control of any such claim, demand or suit.</p>
	<p>This section does not impose additional indemnification requirements for institutions that have separate, current and written agreements with The College Roar.</p>
	<p>9. GENERAL PRACTICES REGARDING USE AND STORAGE</p>
	<p>You agree that The College Roar may from time to time establish and modify in its sole discretion general practices and limits concerning use of the Services including, without limitation, the order form procedures, document delivery options, and timeliness guarantees (if any). You agree that The College Roar reserves the right to log off Registered User accounts that are inactive for an extended period of time at its sole discretion.</p>
	<p>The College Roar may use various ways of verifying information that users have provided. However, none of those ways are perfect, and you agree that The College Roar and its suppliers will have no liability to you arising from any incorrectly verified information.</p>
	<p>10. TERMINATION</p>
	<p>Unless you have agreed to a specific contract term with The College Roar, you may terminate your Registered User account at any time for any reason by sending an email to The College Roar through the contact form requesting such termination. You agree that The College Roar, in its sole discretion and without notice or liability to you or any third party, may terminate your Registered User account if The College Roar believes that you have violated or acted inconsistently with any term of this Agreement. Termination of this Agreement will not relieve you of any liabilities or obligations accrued on or before the date of termination, or limit any other remedies available to The College Roar arising out of your breach of this Agreement. Your indemnification obligations under Sections 8 and 12 will continue after any termination of this Agreement.</p>
	<p>11. LINKS TO/FROM OTHER SITES</p>
	<p>For your convenience, The College Roar may provide links to other Internet sites that The College Roar does not maintain. You should not interpret any link to/from other sites as indicating that The College Roar sponsors or endorses the sites or their materials or that the sites are affiliated with The College Roar in any manner. The College Roar is not responsible for anything contained on such sites and makes no warranties or representations about the contents, products or services offered on such sites. The College Roar is not responsible for and makes no warranties or representations about the content, products or services offered on any sites that you may elect to use in connection with this site.  You agree that it is impossible for The College Roar to monitor such materials and that you access these materials at your own risk.</p>
	<p>12. INTELLECTUAL PROPERTY, COPYRIGHT AND TRADEMARK NOTICE</p>
	<p>The College Roar, its affiliates and licensors retain all right, title and interest in and to the Site, the Services, all Content provided on the Site (excluding third party Content, if any), and the business process, procedures, methods and techniques used on or in connection with the Site and the Services, and all patent rights, copyrights, trademark rights, trade secret rights and other proprietary rights therein or related thereto (collectively, the &quotIntellectual Property&quot). You may not modify, publish, transmit, transfer or sell, license, rent, lease, reproduce, create derivative works from, distribute, perform, link, display, or in any way exploit the Intellectual Property, in whole or in part, except as expressly permitted in this Agreement or with the prior written consent of The College Roar. Subject to any third-party license restrictions, you may copy and create derivative works of the Content displayed on the Site solely for your personal, non-commercial, educational use, provided that you do not remove any trademarks, copyright notices or any other notice contained in such Content. You agree not to modify any Site Content, or Site or Services object code or source code in any manner or form, or to use modified versions of such Content or code for any reason including, without limitation, for the purpose of obtaining unauthorized access to the Services. You agree not to access the Services by any means other than through the interface that is provided by The College Roar for use in accessing the Services. The use of any The College Roar (or any The College Roar affiliate or licensor) trademark or service mark without The College Roar&rsquo;s (or the appropriate owner&rsquo;s) express written consent is strictly prohibited.</p>
	<p>The rights granted to you in this Agreement are subject to the following restrictions: (a) you shall not frame or utilize framing techniques to enclose any trademark, logo, or other Intellectual Property (including images, text, page layout or form) of The College Roar; (b) access the Intellectual Property in order to build a similar or competitive website or service (c) you shall not use any metatags or other &quothidden text&quot using The College Roar&rsquo;s name or trademarks; or (d) you shall not use any manual or automated software, devices or other processes (including but not limited to spiders, robots, scrapers, crawlers, avatars, data mining tools or the like) to &quotscrape&quot or download data from any web pages contained in the Site. Any future release, update or other addition to the Intellectual Property shall be subject to this Agreement. The College Roar, its suppliers and service providers reserve all rights not granted in this Agreement. Any unauthorized use of the Site or the Services terminates the licenses granted by The College Roar pursuant to this Agreement.</p>
	<p>The Site, Services, and Intellectual Property may contain Content provided by other users. The College Roar is not responsible for and does not control such Content. The College Roar has no obligation to review or monitor, and does not approve, endorse or make any representations or warranties with respect to any other user&rsquo;s Content. You use all such Content and interact with other users at your own risk. Your interactions with other users are solely between you and the other user and we are under no obligation to become involved. You agree that The College Roar will not be responsible for any liability incurred as the result of such interactions.</p>
	<P>You agree that submission of any ideas, suggestions, documents, and/or proposals to The College Roar through its suggestion, feedback, wiki, forum or similar pages (&quotFeedback&quot) is at your own risk and that The College Roar has no obligations (including without limitation obligations of confidentiality) with respect to such Feedback. You represent and warrant that you have all rights necessary to submit the Feedback. You hereby grant to The College Roar a fully paid, royalty-free, perpetual, irrevocable, worldwide, non-exclusive, and fully sublicensable right and license to use, reproduce, perform, display, distribute, adapt, modify, re-format, create derivative works of, and otherwise commercially or non-commercially exploit in any manner, any and all Feedback, and to sublicense the foregoing rights, in connection with the operation and maintenance of the Site and the Services.
	<p>13. DISCLAIMERS</p>
	<p>YOU EXPRESSLY UNDERSTAND AND AGREE THAT:</br>
	(a) THE SITE AND THE SERVICES ARE PROVIDED ON AN &quotAS IS&quot AND &quotAS AVAILABLE&quot BASIS. THE COLLEGE ROAR EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT AS TO THE SITE AND ITS CONTENT, AND THE SERVICES.</br>
	(b) THE COLLEGE ROAR AND YOU, THE COLLEGE ROAR MAKES NO REPRESENTATION OR WARRANTY THAT: (I) THE SITE OR THE SERVICES WILL MEET YOUR EXPECTATIONS OR REQUIREMENTS, (II) THE SITE OR THE SERVICES WILL BE UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE, (III) ANY RESULTS OR INFORMATION THAT MAY BE OBTAINED FROM THE USE OF THE SITE OR THE SERVICES WILL BE ACCURATE, TIMELY OR COMPLETE, AND (IV) ANY ERRORS IN ANY SOFTWARE USED ON THE SITE OR IN CONNECTION WITH THE SERVICES WILL BE CORRECTED. FROM TIME TO TIME, THE COLLEGE ROAR MAY OFFER NEW &quotBETA&quot FEATURES OR TOOLS WITH WHICH ITS USERS MAY EXPERIMENT. SUCH FEATURES OR TOOLS ARE OFFERED SOLELY FOR EXPERIMENTAL PURPOSES AND WITHOUT ANY WARRANTY OF ANY KIND, AND MAY BE MODIFIED OR DISCONTINUED AT THE COLLEGE ROAR&rsquo;S SOLE DISCRETION. THE PROVISIONS OF THIS SECTION APPLY WITH FULL FORCE TO SUCH FEATURES OR TOOLS.</br>
	(c) EXCEPT AS MAY BE SET FORTH IN A SEPARATE WRITTEN AGREEMENT BETWEEN THE COLLEGE ROAR AND YOU, THE COLLEGE ROAR IS NOT RESPONSIBLE AND WILL HAVE NO LIABILITY FOR: (I) HARDWARE, SOFTWARE, OTHER ITEMS OR ANY CONTENT, SERVICES OR PRODUCTS PROVIDED BY ANY PERSONS OR ENTITIES OTHER THAN THE COLLEGE ROAR, (II) DAMAGES OF ANY KIND THAT RESULT FROM THE DOWNLOADING OF ANY DATA, PROGRAMS OR ANY OTHER MATERIALS ON THE SITE OR THROUGH THE SERVICES, OR (III) THE FAILURES OF THE INTERNET OR ANY DATA OR TELECOMMUNICATIONS EQUIPMENT, SYSTEM OR NETWORK USED IN CONNECTION WITH THE SITE OR THE SERVICES.</p>
	<p>14. LIMITATION OF LIABILITY</p>
	<p>YOU EXPRESSLY UNDERSTAND AND AGREE THAT NEITHER THE COLLEGE ROAR NOR ITS AFFILIATES WILL BE LIABLE WITH RESPECT TO ANY MATTER OF THIS AGREEMENT UNDER ANY LEGAL THEORY (INCLUDING NEGLIGENCE) FOR: (I) ANY AMOUNT IN EXCESS OF TWENTY-FIVE U.S. DOLLARS ($25), (II) ANY LOST DATA OR SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES OF ANY CHARACTER INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OF GOODWILL, COMPUTER FAILURE OR MALFUNCTION, OR ANY AND ALL OTHER COMMERCIAL DAMAGES OR LOSSES, EVEN IF THE COLLEGE ROAR OR ITS AFFILIATES WERE ADVISED OF THE POSSIBILITY OF SUCH DAMAGES, OR (III) THE COST OF PROCURING SUBSTITUTE SERVICES.</p>
	<p>15. EXCLUSIONS AND LIMITATIONS
	<p>THE LIMITATIONS OF DAMAGES SET FORTH ABOVE ARE FUNDAMENTAL ELEMENTS OF THE BASIS OF THE BARGAIN BETWEEN THE COLLEGE ROAR AND YOU. IF ANY OF THE SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSIONS OR LIMITATIONS SET FORTH IN SECTIONS 13 AND 14 ARE FOR ANY REASON HELD TO BE INVALID OR UNENFORCABLE, THIS AGREEMENT AND THE BALANCE OF THE PROVISIONS HEREOF SHALL NONETHELESS REMAIN IN EFFECT.</p>
	<p>YOU AND THE COLLEGE ROAR AGREE THAT ANY CAUSE OF ACTION ARISING OUT OF OR RELATED TO THESE TERMS, THE SITE, THE SERVICES OR THE CONTENT MUST COMMENCE WITHIN ONE (1) YEAR AFTER THE CAUSE OF ACTION ACCRUES. OTHERWISE, SUCH CAUSE OF ACTION IS PERMANENTLY BARRED.
	<p>16. GENERAL INFORMATION</P>
	<p>This Agreement constitutes the entire agreement between you and The College Roar, superseding any prior agreements between you and The College Roar. This Agreement is governed by and construed in accordance with the laws of the State of Pennsylvania without regard to its conflict of laws provisions. You agree to submit to the personal and exclusive jurisdiction of the courts located within the County of Bucks, Pennsylvannia. The failure of The College Roar to exercise or enforce any right or provision of this Agreement shall not constitute a waiver of such right or provision. If any provision of this Agreement is found by a court of competent jurisdiction to be invalid, that provision will be enforced to the maximum extent permissible and the remaining provisions will remain in full force and effect. These Terms, and your rights and obligations hereunder, may not be assigned, subcontracted, delegated, or otherwise transferred by you without The College Roar&rsquo;s prior written consent, and any attempted assignment, subcontract, delegation, or transfer in violation of the foregoing will be null and void. Any waiver or failure to enforce any provision of this Agreement on one occasion will not be deemed a waiver of any other provision or of such provision on any other occasion.</p>
	<p>The communications between you and The College Roar use electronic means, whether you visit the Site or send The College Roar e-mails, or whether The College Roar posts notices on the Site or communicates with you via e-mail. For contractual purposes, you (1) consent to receive communications from The College Roar in an electronic form; and (2) agree that all terms and conditions, agreements, notices, disclosures, and other communications that The College Roar provides to you electronically satisfy any legal requirement that such communications would satisfy if it were to be in writing. The foregoing does not affect your statutory rights.</P>
	<p>You hereby release The College roar and its employees, agents, officers, and directors and their successors from claims, demands, any and all losses, damages, rights, and actions of any kind, including personal injuries, death, and property damage, that is either directly or indirectly related to or arises from any interactions with or conduct of other Site users or third party websites of any kind arising in connection with or as a result of your these Terms or your use of the Site  or the Services. If you are a California resident, you hereby waive California Civil Code Section 1542, which states, &quotA general release does not extend to claims which the creditor does not know or suspect to exist in his favor at the time of executing the release, which, if known by him must have materially affected his settlement with the debtor.</p>
	<p>The College Roar shall not be liable for any delay or failure to perform resulting from causes outside its reasonable control, including, but not limited to, acts of God, war, terrorism, riots, embargos, acts of civil or military authorities, fire, floods, accidents, strikes or shortages of transportation facilities, fuel, energy, labor or materials.</P>
	<p>Where The College Roar requires that you provide an e-mail address, you are responsible for providing The College Roar with your most current e-mail address. In the event that the last e-mail address you provided to The College Roar is not valid, or for any reason is not capable of delivering to you any notices required/ permitted by these Terms, The College Roar&rsquo;s dispatch of the e-mail containing such notice will nonetheless constitute effective notice. You may give notice to The College Roar at the following address: The College Roar. Such notice shall be deemed given when received by The College Roar by letter delivered by nationally recognized overnight delivery service or first class postage prepaid mail at the above address.</p>
	<p>This Site can be accessed from countries around the world and may contain references to services and Content that are not available in your country. These references do not imply that The College Roar intends to announce such services or Content in your country. The Site and Services are controlled and offered by The College Roar from its facilities in the United States of America. The College Roar makes no representations that the Site or the Services are appropriate or available for use in other locations. Those who access or use the Site or the Services from other jurisdictions do so at their own volition and are responsible for compliance with local law.</p>
	<p>You may not use, export, import, or transfer the Intellectual Property except as authorized by U.S. law, the laws of the jurisdiction in which you obtained the Intellectual Property, and any other applicable laws.</p>
	<p>17. ARBITRATION</p>
	<p>Any claim or dispute (excluding claims for injunctive or other equitable relief as set forth below) in connection with this Agreement where the total amount of the award sought is less than Five Thousand U.S. Dollars (US $5,000.00) may be resolved in a cost effective manner through binding non-appearance-based arbitration, at the option of the party seeking relief. Such arbitration shall be initiated through an established alternative dispute resolution provider (&quotADR Provider&quot) that offers arbitration as set forth in this section and under the rules of such ADR Provider, except to the extent such rules are in conflict with this Agreement. The party demanding arbitration will propose an ADR Provider and the other party shall not unreasonably withhold consent to use such ADR Provider. The ADR Provider and the parties must comply with the following rules: (1) the arbitration shall be conducted by telephone, online and/or be solely based on written submissions, the specific manner shall be chosen by the party initiating the arbitration; (2) all arbitration proceedings shall be held in English; (3) the arbitration shall not involve any personal appearance by the parties or witnesses unless otherwise mutually agreed by the parties; and (4) any judgment on the award rendered by the arbitrator may be entered in any court of competent jurisdiction. Each party shall bear its own costs (including attorney fees) and disbursements arising out of the arbitration, and shall pay an equal share of the fees and costs of the ADR Provider. Notwithstanding the foregoing, The College Roar may seek injunctive or other equitable relief to protect its intellectual property rights in any court of competent jurisdiction. Please note that the laws of the jurisdiction where you are located may be different from Pennsylvania law, including the laws governing what can legally be sold, bought, exported, offered or imported. You shall always comply with all the international and domestic laws, ordinances, regulations and statutes that re applicable to your use of the Site and the Services.</p>
	<p>Any other Dispute (including whether the claims asserted are arbitratable) shall be referred to and finally determined by arbitration in accordance with the American Arbitration Association Commercial Arbitration Rules (the &quotRules&quot) and shall be administered by the Philadelphi, Pennsylvania office of the American Arbitration Association (the &quotAdministrator&quot). To the extent there is any conflict between the provisions set forth in this section and any procedural or other rules issued by the Administrator, this section will control. The location of the arbitration will be Philadelphia, Pennsylvania USA. The Dispute(s) shall be submitted to a single arbitrator (&quotArbitrator&quot) chosen by the parties or selected by the parties from a list of potential arbitrators provided by the Administrator. The Administrator shall provide such list to the parties 10 days after request by either party. Should the parties be unable to agree on a choice of arbitrator within 10 days after receipt of the list from the Administrator, then the Administrator will select the Arbitrator. The arbitral proceedings, and all pleadings and written evidence will be in the English language. Any written evidence originally in a language other than English will be submitted in English translation accompanied by the original or true copy thereof. The English language version will control. Each party shall bear its own attorney&rsquo;s fees, costs, and disbursements arising out of the arbitration, and shall pay an equal share of the fees and costs of the Administrator and the Arbitrator; provided, however, the Arbitrator shall be authorized to determine whether a party is the prevailing party, and if so, to award to that prevailing party reimbursement for its reasonable attorneys&rsquo; fees, costs and disbursements (including, for example, expert witness fees and expenses, photocopy charges, travel expenses, etc.), and/or the fees and costs of the Administrator and the Arbitrator. The Arbitrator shall issue a written award and statement of decision describing the essential findings and conclusions on which the award is based, including the calculation of any damages awarded. The Arbitrator will not have authority to award damages in excess of the amount, or other than the types, allowed by Section 9 of this Agreement. Judgment on the award of the Arbitrators may be entered by any court of competent jurisdiction. The Arbitrator also shall be authorized to grant any temporary, preliminary or permanent equitable remedy or relief it deems just and equitable and within the scope of this Agreement, including, without limitation, an injunction or order for specific performance. The arbitration award shall be final and binding upon the parties without appeal or review except as permitted by Pennsylvania law or United States Federal law.</p>
	<p>By using the Site or the Services in any manner, you agree to the above arbitration provision. In doing so, YOU GIVE UP YOUR RIGHT TO GO TO COURT to assert or defend any claims between you and The College Roar (except for matters that may be taken to small-claims court). YOU ALSO GIVE UP YOUR RIGHT TO PARTICIPATE IN A CLASS ACTION OR OTHER CLASS PROCEEDING. Your rights will be determined by a NEUTRAL ARBITRATOR, NOT A JUDGE OR JURY. You are entitled to a fair hearing before the arbitrator. The arbitrator can grant any relief that a court can, but you should note that arbitration proceedings are usually simpler and more streamlined than trials and other judicial proceedings. Decisions by the arbitrator are enforceable in court and may be overturned by a court only for very limited reasons.</p>
	<p>18. VIOLATIONS</p>
	<p>Please report any violations of this Agreement to our Customer Service department through the contact form.</p>
	<p>&copy;2015 The College Roar</br></br>
	Support</br>
	Privacy Policy</br>
	<a href="http://thecollegeroar.com/terms_of_use.php">Terms of Use</a></br>
	<a href="http://www.thecollegeroar.com/contactform.php">Contact Us</a></br>
	Careers</br>
	<a href="http://www.thecollegeroar.com/about.php">About Us</a></br>
	Blog</br>
  </div> 
			
		</div>

		<div id="news">
			<div class="panel-heading">
            	<h3 class="panel-title">
            		<ul>
            			<li><img 	src="Images/Social/Twitter_570625.png" 
							width="50px"
							height="auto"></li>
						<li>The College Roar Live</li>	
					</ul>
            	</h3>
            </div>
            <div class="panel-body">
            	<div class="twitter">
			        <a class="twitter-timeline"
			          href="https://twitter.com/thecollegeroar"
			          data-widget-id="597082223712608257"
			          data-screen-name="thecollegeroar"
			          data-show-replies="false"
			          data-tweet-limit="5">
			          Tweets by @thecollegeroar
			        </a>
			        <script>
			          !function(d,s,id){
			            var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';
			            if(!d.getElementById(id)){
			              js=d.createElement(s);
			              js.id=id;
			              js.src=p+"://platform.twitter.com/widgets.js";
			              fjs.parentNode.insertBefore(js,fjs);
			            }
			          }
			          
			          (document,"script","twitter-wjs");
			        </script>
		      	</div>
			</div>
         </div>
	</div>
  </body>
</html>

